### PR TITLE
Website search

### PR DESCRIPTION
**Pull request by benjaminmodayil**
Implemented search functionality with Algolia.

**Questions**
1. Should we have a _role_ variable in the frontmatter for each apprenticeship? Some of these companies may have multiple roles they are trying to fill,
_ie: front-end, back-end, design, UX, and PM. Adding this could help with the filtering down of results._

2. Also, do we need any other type of filtering UI? The search bar filters based on any text added to it. So you could search by location or keyword and results will appear based on that search. 

3. Branch deploys at the moment aren't working... Mainly because I'm confused on the final structure of the project. Right now, it's in a `dir/website/` folder. Will this be where it ultimately lives, or will it be in the base `dir/` folder? Are you okay with me taking off the "redirect" in the base `index.html` file or should we be merging into a generic `website`  branch until ultimately bringing it in the `master` branch?

4. Design: I’m using some generic classes from the Hugo theme “Paper” as mentioned in the issues. But even then, it’s pretty bland at the moment. Are you looking for design direction (read below)?

I’ve been working on my design skills outside of dev work and I’m trying to move into a front-end role with design capabilities. So **purely as a design exercise** I used what I knew about the apprenticeship repo and gave myself a design exercise in Sketch (still working on it of course).

But is the below, in-progress, design a direction you think you’d like for the site? I’m happy to go back and forth on this as right now it's just purely a **very-much in-progress** design exercise for me at the moment. But if not, no worries! I’m just working on bettering my design skills and thought I'd bounce the idea off you.

Right now I'm trying to model it having the listings, a more in-depth introduction to "What is an apprenticeship?" (from the repo), a list of contributors, and a listing of resources. Let me know if you'd be interested in working off something like this for the website.

_Note: Illustrations are MIT licensed from [Undraw](https://undraw.co)_
design-exercise-job-board

---

## ✅️ By submitting this PR, I have verified the following

* [✅️] Checked to see if a similar PR has already been opened 🤔️
* [✅️] Reviewed the contributing guidelines 🔍️
* [✅️] Added my name to the bottom of the list under the **Credits** section in the `README.md` with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@benjaminmodayil Let me look into deployment this weekend but I can answer your questions for now.

1. Yes, I think it would be good to have a role or type variable so it's easier to filter by what type of apprenticeship the company is looking for. 

We'll note that in `CONTRIBUTING.md` that apprenticeships should list out the ones from a certain list - something like this.

```
type: 
	- front-end
	- back-end
	- ux design
	- ui design
	- product management
	- quality assurance
```

2. Let's keep it minimal for now so no other filtering is needed and we can just note that the user can search by location, role, etc. by putting in the text. 

What could be great though is if we get a filter drop-down for locations but I think it looks fine as is.

3. I'm thinking the final project structure would look something like this:

```
├── .github
|  ├──  CODE_OF_CONDUCT.md         // code of conduct
|  ├──  CODEOWNERS                 // automatic reviewers for certain files and directories
|  ├──  CONTRIBUTING.md            // how to contribute
|  ├──  ISSUE_TEMPLATE.md          // template for new issues
|  ├──  PULL_REQUEST_TEMPLATE.md   // template for new pull requests
|  └──  stale.yml                  // configuration for Stale bot
├── .vscode
|  └──  settings.json       // VS Code workspace settings
├── dist                    // (ignored) static files generated and served through Netlify using npm start or npm build
├── site
|  ├── archetypes           // default post formats
|  ├── content              // content goes here (Markdown files with posts and pages)
|  ├── layouts              // HTML Liquid templates for pages
|  ├── static               // files that go into root of dist directory
|  └── config.toml          // configuration file (Hugo)
├── src
|  ├── img                  // images are optimized through Gulp
|  ├── js                   // compressed and transpiled to a single JS file
|  └── sass                 // compressed and compiled to a single CSS file
├── .babelrc                // configuration for Babel
├── .editorconfig           // configuration for editors
├── .eslintrc               // configuration for ESLint
├── .gitignore              // ignored files and folders
├── .nvmrc                  // configuration for NVM
├── .prettierrc             // configuration for Prettier formatter
├── CNAME                   // domain name
├── gulpfile.babel.js       // configuring Gulp build process for assets
├── LICENSE                 // repo license
├── netlify.toml            // configuration for Netlify deployment
├── package.json            // managing NPM packages
├── README.md               // overview
├── renovate.json           // configuration for Renovate bot
├── webpack.dev.js          // Webpack build configuration for local development
└── webpack.prod.js         // Webpack build configuration for production
```

4. THIS LOOKS AMAZINGGGGG. In terms of design direction, this is almost exactly what I was looking for except I was thinking that the page could be structured in a single page view instead without any links necessary. 

This way, the user can just get all the context they need right away and then start sifting through apprenticeships. In other words, the layout would be:

- Hero - title, subtitle & two buttons on top right (Contribute and GitHub)
- About - what is an apprenticeship
- Apprenticeships - listing them out in cards with the search bar
- Resources - just listing out some links
- Contributors - giving kudos to our many contributors - we can even integrate this a little with GitHub maybe so they just include their GitHub username somewhere and it will populate it OR we could create a `contributors` section with Hugo and everyone would create their own Markdown file with their info and we populate that.

Also for the icons - we don't want to use Font Awesome since it's pretty heavy - we instead just want to pluck out the SVG for the icons we end up using so the website is more performant.

I'm pretty open to suggestions on design direction though.

One thing I would note, however, is that it might be useful to test the accessibility of the colors with an auditing tool like [Lighthouse](https://developers.google.com/web/tools/lighthouse/) - I think some of the colors might need to be darker to pass the accessibility audits down the line.

---

Anywho this looks bomb!! Super excited for getting this merged in once we iron out the kinks. Hoping I can look at it more this weekend.

💯

**Comment by benjaminmodayil** [comment]
Awesome. 😊

I'll work more on the design and probably bring it up in the Github issue with updates. I'm guessing doing some of this in the PR is a little difficult.

I actually have no idea how to use Font Awesome, so this works out for me, haha. I was using SVG icons from a library I purchased a while back. None of the design is actually implemented in the code by the way, this was just a screenshot from Sketch.

Yeah I was thinking the same about the color contrast. I'll rework those.

Everything else you said sounds good 👍

**Comment by fvcproductions** [comment]
@benjaminmodayil Just a heads up that I didn't get a chance to look at this quite yet but it's definitely in the back of my mind! 😬 

I did end up giving you a shout out though in a conversation I had with the creator of apprenticeship.io - Kamrin Klauschie - just letting her know why I love the open source community because of how people can band together and get shit done.

Anyways, thanks again for accelerating the process of getting a website started for these apprenticeships - hope to contribute to this project myself very soon.

**Comment by benjaminmodayil** [comment]
@fvcproductions No worries! I'm still bouncing around with your feedback with the design when I have time. Hope to have another iteration with your feedback implemented soonish for another review + rework.

Ah, I appreciate the shoutout! 😄For getting things actually done, I've been using live-streaming as an accountability tool to continue work my own site and also some of the work so far on this repository. I like to think of live-streaming as "open-source+" since it's open-source, but then viewable by the public.

No problem, thanks for making this repository an open-source project. I've been wanting to contribute more to open-source and this repository was the perfect opportunity!

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging 9c3c6e45acb0b129cf1e4ff97fd7ca1d7f3bb76f into 7374679cffca08f5ac2a8f137b53bcf8deee630c - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships/rev/pr-0b4de3edab4baed28408dd3870cfe2db9314536f)

**new alerts:**

* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
@benjaminmodayil All the issues are related to `vendor.css` which we'll be removing in favor for using a CSS framework like Bulma instead. https://bulma.io/ 

Deploy preview works now! https://deploy-preview-18--apprenticeships.netlify.com/

**Comment by fvcproductions** [comment]
Fixing LGTM issue with links

**Comment by fvcproductions** [comment]
Going to move around some folders

**Pull request merged**
